### ISSUE TITLE
Add a bit extra CSS for the list table

### ISSUE THREAD

**Issue by abjerner** [skybrud/Skybrud.ImagePicker#13]
As a result of Umbraco's styling for `.table`, the list gets a double border, which looks a bit wrong. Could be fixed with adding a rule like as shown below to our stylesheet:

```css
.SkybrudImagePickerList > .table {
    border: 0;
}
```

**Before:**
![image](https://user-images.githubusercontent.com/3634580/48124176-f8556180-e27b-11e8-9747-03392c888c1f.png)

**After:**
![image](https://user-images.githubusercontent.com/3634580/48124197-030ff680-e27c-11e8-831e-f0f532d8e58b.png)
